### ISSUE TITLE
App Request Invalid

### ISSUE THREAD

**Issue by cosmicqbit** [dishapatel010/gdriveDL#1]
I configured Client ID & Secret value properly besides subdomain URL but I keep getting this error.
![image](https://user-images.githubusercontent.com/75565639/229306151-d6e89aba-4437-4e23-8274-982406d20b0c.png)
![image](https://user-images.githubusercontent.com/75565639/229306243-e75c9e72-49ef-4230-99bc-cb34e3865897.png)

**Comment by cosmicqbit** [comment]
Can you add a README to repo please, elaborating on how to configure vars. Thank you.

**Comment by dishapatel010** [comment]
Check out readme.
